name: Polaris SAST and SCA Buildless Scan
                                                                                                                                                                                                                                         
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]

jobs:
  polaris-scan:
    runs-on: [ ubuntu-latest ]
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodejs-npm

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  
                                                                                                                                                                                                                                        
    - name: Polaris SAST and SCA Buildless Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        polaris_assessment_types: "SCA,SAST"
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
